### PR TITLE
 Remove extra BufReader, BufWriter, type fish 

### PR DESCRIPTION
**Pull request by louy2**
The title is what I set out to do but I set up my editor so it auto-formats the source and before I realized I made all my fixes based on `rustfmt` formatted code 😞 

I decided to at least separate out the formatting change to its own commit. If you don't like it let me know.

### CODE REVIEW

**Comment by koraa** [comment]
What purpose does removing the output buffer serve?

**Comment by louy2** [comment]
> What purpose does removing the BufWriter serve? I did use it intentionally to limit the number of write() system calls…

[`stdin.lock()`] gives you a `StdinLock`, which implements BufRead, meaning that it is already buffered, so no need to add another buffer on top. Let me also quote the [source]:

```rust
pub struct StdinLock<'a> {
    inner: MutexGuard<'a, BufReader<Maybe<StdinRaw>>>,
}
```

[`stdin.lock()`]: https://doc.rust-lang.org/std/io/struct.Stdin.html#method.lock

> maybe you could try to provide a config file to make these look better? I am thinking specifically of the increased match statement verbosity in some cases

Of course! If you can give me an example so I can have a better idea of what you mean.
[source]: https://doc.rust-lang.org/src/std/io/stdio.rs.html#196-198

**Comment by koraa** [comment]
> [`stdin.lock()`](https://doc.rust-lang.org/std/io/struct.Stdin.html#method.lock) gives you a `StdinLock`, which implements BufRead, meaning that it is already buffered, so no need to add another buffer on top. Let me also quote the [source](https://doc.rust-lang.org/src/std/io/stdio.rs.html#196-198):

Bloody hell, you are right! I completely overlooked this…what a weird design choice…
Actually it seems stdin()/stdout()/stderr(), which means we have to also implement a rawStdin() for use with the zero copy reader…

Would you be willing to do add this PR too?

> Of course! If you can give me an example so I can have a better idea of what you mean.

Making sure all braces in match statements are on the same line as the match should suffice. Please also open a dedicated pr for the style changes and add a rust lint config to at least signal that we have a defined code style, even if it's the default one (at the moment).

**Comment by koraa** [comment]
Manually merged! Applied rustfmt to all rust files, did not use a `rawStdin()` implementation, because that turned out to not really improve performance.

Thanks for your contribution!

**Comment by dippi** [comment]
> which means we have to also implement a rawStdin() for use with the zero copy reader…

`BufReader` uses directly the slice received as parameter if it's larger than the internal buffer avoiding the copy. https://doc.rust-lang.org/src/std/io/buffered.rs.html#242-248
That could explain why there wasn't a noticeable performance improvement.

**Pull request closed without merging**
