### PR TITLE
Implement -s,--sort and -S,--sort-descending for output ordering

### LINKED ISSUE #9: Sort options
It should be possible to sort output by duplicate count (rank mode `--rank` or `--reverse-rank`)

### PR DESCRIPTION
**Pull request by alexmaco**
Fixes #9 , as I've also found the need to have a sorting option myself.

The flag names are those suggested in #9, but that's open to bikeshedding.

### CODE REVIEW

**Comment by koraa** [comment]
First of all, thank you very much for contributing!

# Requirements before merge

I like your code, it looks very good. There are just two changes I will require before merging:

1. First of all, the bikeshed; I would prefer something like --sort/-s --sort-descending/-S (1) because descending is more immediately descriptive compared to `reverse`and (2) because the idiom it replaces is `huniq | sort`. Which idiot even suggested --r…oh it was me ;)
2. As horrible as the tests admittedly are (I solemnly vow to introduce improvements in that area), please add some very simple tests.

What I particularly like about your implementation is the usage tuples to represent the values in the array and the decomposition into sort_and_print and print_out btw!

# Ponderings

I like to split my reviews into requirments & ponderings. The ponderings are usually a lot, may be open ended and represent the sort of philosophical questions often best left unanswered by engineers trying to get actual work done; as such you are entirely free to disregard them:

1. I keep wondering if there isn't a more efficient way to do this. We're effectively copying all the data from the hash map into a second memory buffer and then sort it. That is three separate passes over the data and 2x the minimum memory usage…optimally we would just reuse the same memory buffer and sort the data in there, but that would require a specialized container…the hashbrown crate (which is actually the hash map used by the std lib right now) features a Raw API which could be used to the end. I think this could really provide an algorithmic advantage over `huniq | sort`.
2. How about moving into the vector? No need to keep hash map around…
3. How about allocating the correctly sized vector up front before sorting using `reserve()`? No need to allocate multiple times…
4. A count_sort_cmd might be nicer than having an Option

**Comment by alexmaco** [comment]
Firstly, I'm very glad to see tests are welcome ! I normally like to do TDD, but I reluctantly did not add tests here since there weren't any in the first place for the application code :laughing: . I could add regular `#[test]`s that just check the inner functionality, but for cli apps I found that [assert_cli](https://docs.rs/assert_cli/) works great for end-to-end testing, including the cli arguments. Do you have any preference between these ?

Second, yes, `-s,--sort` and `-S,--sort-descending` make more sense, I'll switch to those.

Third, the performance aspects.

1. The thing about the sorting step is that the `Vec` contains tuples of `u64`s and `&[u8]` slices, that is, the lines themselves are not copied over, they are only referenced. The memory is still owned by the `Vec<u8>` keys in the original `HashMap`, and is never moved or duplicated. So effectively, the sorting operates on 24 byte entries (on a 64bit OS). The memory complexity of this is not M(n), it's rather M(n)/M(average_line_length), which is more efficient for longer lines, and less efficient for short ones.

2. Draining the `HashMap` and moving into a `Vec` might be worth it for other reasons, but it won't decrease the maximum memory usage. The `Vec` will be preallocated to full size at the start, while the `HashMap` still has all the elements, so the maximum memory usage may be a little higher (since `size_of::<Vec<_>>() == 24` and `size_of::<&[u8]>() == 16`.

3. the `reserve` trick is done automatically by `collect` (actually, by things called from `Vec`s `FromIterator` impl, because the iterators over the `HashMap` implement `fn size_hint`.

The most efficient way to do this would be to use a specialized container, with a `HashMap` interface but a linear backing store of `Vec<(K, V)>`, into which it can be converted once the lookup is done and sorting is needed. Something akin to `boost::flat_map`, but with a hash function instead of ordering. If you know of any such crate out there I'd gladly use it, but i haven't found one yet. Then again maybe I need to eventually write it myself :laughing:

**Comment by koraa** [comment]
> Firstly, I'm very glad to see tests are welcome ! I normally like to do TDD, but I reluctantly did not add tests here since there weren't any in the first place for the application code laughing . I could add regular `#[test]`s that just check the inner functionality, but for cli apps I found that [assert_cli](https://docs.rs/assert_cli/) works great for end-to-end testing, including the cli arguments. Do you have any preference between these ?

That assert_cli thing sounds awesome! The shell based tests are kind of awful. Honestly, I wrote this as the first thing after I started coding rust; 10y of C++ experience really help in creating extremely efficient code but that entire rust ecosystem…I caught me gleeful!

>     1. The thing about the sorting step is that the `Vec` contains tuples of `u64`s and `&[u8]` slices, that is, the lines themselves are not copied over, they are only referenced. The memory is still owned by the `Vec<u8>` keys in the original `HashMap`, and is never moved or duplicated. So effectively, the sorting operates on 24 byte entries (on a 64bit OS). The memory complexity of this is not M(n), it's rather M(n)/M(average_line_length), which is more efficient for longer lines, and less efficient for short ones.

I don't quite understand this point. I don't object to using a sort function; it's IMO the better choice here…
My point 1. was not about algorithmic complexity, it was about buffer reuse…you are right that `Vec<u8>` requires 24 bytes while `&[u8]` requires just 16. There are ways around that though, we could use arena allocation (possibly zero terminated) + maybe short string optimization…but yeah, this is kind of out of scope…

>     2. Draining the `HashMap` and moving into a `Vec` might be worth it for other reasons, but it won't decrease the maximum memory usage. The `Vec` will be preallocated to full size at the start, while the `HashMap` still has all the elements, so the maximum memory usage may be a little higher (since `size_of::<Vec<_>>() == 24` and `size_of::<&[u8]>() == 16`.

You are correct! My point was more about code cleanliness, but yeah, sorting 24 byte tokens might beat 32 byte sorting tokens, on the other hand it might not because of alignment issues…we'd have to benchmark…on that note swapping the memory layout migth yield some improvements

>     3. the `reserve` trick is done automatically by `collect` (actually, by things called from `Vec`s `FromIterator` impl, because the iterators over the `HashMap` implement `fn size_hint`.

Great! I did not know that…actually I could have red the collect docs…

> The most efficient way to do this would be to use a specialized container, with a HashMap interface but a linear backing store of Vec<(K, V)>, into which it can be converted once the lookup is done and sorting is needed. Something akin to boost::flat_map, but with a hash function instead of ordering. If you know of any such crate out there I'd gladly use it, but i haven't found one yet. Then again maybe I need to eventually write it myself laughing

As far as I could see from reading the code, I believe hashbrown uses open addressing with linear probing; so no indirection or multiple buffers. The buckets are layed out linearly in memory followed by a bitarray indicating which slots are used…I think it would be possible to implement buffer reuse with this by taking ownership of the memory buffer (`RawTable::data_start()` plus `RawTable::data_end()` to get the buffer followed by `mem::forget()` on the hash table)

I think the buffer reuse as well as the arena allocation are probably better left as the subject of a dark magic optimizations blog post…seems a bit out of sope when I think about it in the morning…

Thanks for your PR! Let's add these tests and then get this thing merged…

**Comment by alexmaco** [comment]
@koraa I've updated the PR. Are there any other changes I should make to it before the merge ?

**Pull request merged**
